### ISSUE TITLE
PCB design

### ISSUE THREAD

**Issue by mesmariusz** [francescovannini/truetape64#1]
As I See PCB / gerbers are missing. I'm going to prepare for myself @ KiCad format. If you are interested I could share it for you.

Is this project well tested / works good enough?

**Comment by francescovannini** [comment]
I didn't bother producing a proper PCB as this was mostly a small experiment / challenge meant to work just for a few days, to recover all the tapes I have. I tested it with tens of tapes; those which were unreliable after the dump, were unreliable also before, using a real C64; but I could recover data from the dump, so I was definitely happy with the results.
I would certainly be interested in the PCB and schematics if you feel like sharing! Thanks!

**Comment by mesmariusz** [comment]
It's great to hear your interface works so much :-) For me this is very nice message, especially because I tried (maybe 25 years ago) the similar solution for LPT port ( https://om.vlip.lv/video/ifxAbwKeGi5f9zE%3D.html ) and it worked for me then (25 years ago). About 3 years ago I tried to do it again (many Datasettes, many retro PC's, and many tapeio.exe revisions) but with no result. I dont know why. Everytime load error and notheing more...

https://www.youtube.com/watch?v=Qw3gm-NW9i0&t=20s&ab_channel=MariuszCiszewski
https://www.youtube.com/watch?v=H0MvUC3SV2U&t=80s&ab_channel=MariuszCiszewski
https://www.youtube.com/watch?v=LFOsX8vCoRA&t=4s&ab_channel=MariuszCiszewski

So if your interface works so nice, and with modern PC's (no LPT needed) then for sure and with a great pleasure I will create the circuit drawing and PCB. 

Nowadays this is really great if every new hardware is "Arduino compatibile" or build based on Adruino. Even I started to like it ;-). It's easier to program (no programmer is needed, no complicated programm environment, just plug the USB cable, run the Aduino IDE, open .ino file, program and that's all :-) I rally started to like it (previously bare microcontrollers and firmware coded @ Bascom AVR ;-) )

My question: could it be possible for you to prepare the firmware version based on e.g. Arduino Nano (or similar)?
Then I could prepare the hardware ready just to put Arduino module in it, program, and that's all. 

If there is any issue to prepare the source @ Arduino language, then of course I can also prepare the documentation (sch, pcb) also for bare microcontroller. 

Generally this is really great job, my congratulations :-) 

Best regards
Mariusz

**Comment by francescovannini** [comment]
Hi Mariusz, 

thanks for the feedback! In fact, if you were thinking about an Arduino-based solution, I believe there is already something like this one https://github.com/sweetlilmre/tapuino

**Comment by mesmariusz** [comment]
This is possible to connect real Datasette to a PC using Tapuino? Probably not ;-) Tapuino is an emulator / replacement to a real hardware. And I'm searching the nice working solution to connect a real Datasette to a PC. That's quite different topics ;-)

**Comment by francescovannini** [comment]
I know, tapuino is kind of the reverse of truetape64, but looking at this board https://github.com/sweetlilmre/tapuino/wiki I see an edge connector; I'm not sure you can directly hook a Datasette there (maybe the motor 6+ voltage isn't provided yet), however I would say that the Tapuino is probably a better starting point for you than my project, since it's already based on Arduino and it more or less has already the hardware that you need...

**Comment by mesmariusz** [comment]
Ok, I catch your point right now ;-) I will check the hardware, but the hardware is not an issue in a fact.
The most important is to have checked and well tested Arduino code to implement. 
I see your code is also C, so maybe it shouldn't be hard to translate to .ino, but for sure I will find no enough time for that. PCB design is my common daily work right now ;-) It's a several minutes for me. So maybe to make it easier I will prepare the PCB just for bare ATTiny2313 and for Arduino maybe some other day ;-)

**Comment by francescovannini** [comment]
Sure, that would be great! For the code, I think it would not make much sense to port it to Arduino as it's extremely simple as it is already and in general bare C performs a little bit better. If you are into circuit design, maybe you can double check if everything is ok, I've surely missed something, I know at least a couple of decoupling capacitors as someone also noticed on Hackaday...

**Comment by mesmariusz** [comment]
Generally It make a sense, because e.g. Arduino Nano have build in USB to UART converter, is small and maybe even cheaper (aliexpress) than even single ATTiny microcontroller + FTDI converter + breadboard or universal board. And it's easier and faster to build (just put the arduino to almost bare PCB including edge connector to a Datasette), connect USB cable, upload .ino to Arduino ant thst's all. Easy PCB @ 2 USD per 5 pcs of PCB @ jlpcb, probably it's cheaper and more simple way, even more simple than build it on an universal PCB from a few discrette components ;-)

**Comment by francescovannini** [comment]
Precisely! For the hardware what you said it's what Tapuino did ;)

**Comment by mesmariusz** [comment]
Tapuino (PCB including edge connector for Datasette variant) is qite big:
https://github.com/sweetlilmre/tapuino/wiki/Tapuino-1.7.jpg

I could make your hardware design:
https://github.com/francescovannini/truetape64/blob/master/assets/proto_connected.jpg?raw=true

much smaller, even smaller than Tapuino ;-)

DC-DC under or above Arduino Nano (similar size), and  just outstanging edge connector for Datasette. 
So the final size probably Arduino size and outstanding edge connector :-)

**Comment by boelle** [comment]
i just made something in kicad

![image](https://github.com/francescovannini/truetape64/assets/3832239/3a4a8a3a-c533-4fab-bc7a-2c37e380e154)


i'm not a programmer, but what would it take to change  the python code so we could also write to tape?
