### ISSUE TITLE
Support record mode

### ISSUE THREAD

**Issue by heneault** [francescovannini/truetape64#2]
Thank you for this project. I didn't start it but it is on my todo list!

I would like to know if you consider supporting the record mode ? That would increase the old nostalgic effect by having the ability to push a .tap file from the pc to a real tape being recorded by the 1530. Then, the c64 would be able to read back the tape without compatibility issue since it would have been written by the datassette itself.

**Comment by francescovannini** [comment]
Hi! The original purpose of this project was to just dump tapes, not to produce new ones. However, I think with minimal hardware modifications (probably just a couple of extra wires) and a new firmware it would be definitely possible, so why not...
