### ISSUE TITLE
Error sense PIN

### ISSUE THREAD

**Issue by Nanths** [francescovannini/truetape64#3]
Hi!

Thank you and congratulations for this project. It seems that the PIN sense was updated in the python code but it wasn't in readme and schematic file. Can you check it? It has to be PD3 but in schematic and readme says PD2. I spent some hours trying to find why it didn't work and what I did wrong, hehe. 

Btw, it works great :)

**Comment by francescovannini** [comment]
Hey Nanths thanks for spotting this, I've fixed it. 
I had changed the ping last minute in the code but forgot to update the docs, sorry for the time you lost on this.
I hope at least it helped dumping some tapes! :)
